/**
 * medicines_database_enrichment.js
 * Enriquecimento curado do banco de dados — categorias faltantes
 * Produtos reais com preços de referência (Drogasil/Ultrafarma, jul/2025)
 * 
 * Categorias adicionadas:
 *  - Tópicos musculares / analgésicos externos (incl. Salonpas)
 *  - Higiene pessoal (desodorantes, shampoos, sabonetes, absorventes)
 *  - Dermocosméticos (hidratantes, protetores solares, cicatrizantes)
 *  - Suplementos e vitaminas
 *  - Produtos para bebê
 *  - Saúde sexual
 *  - Primeiros socorros / curativos
 *  - Antifúngicos tópicos adicionais
 *  - Termolábeis e equipamentos básicos
 */

const ENRICHMENT_DB = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TÓPICOS MUSCULARES / ANALGÉSICOS EXTERNOS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Salonpas Adesivo Analgésico 10 unidades",
    aliases: ["salonpas", "salompas", "salonpas adesivo", "adesivo analgésico salonpas"],
    price: 29.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Caixa com 10 adesivos",
    unitName: "caixa",
    activeIngredient: "Mentol + Metil Salicilato + Cânfora",
    manufacturer: "Hisamitsu",
    isGeneric: false,
    recipeType: "none",
    tags: ["topico", "muscular", "adesivo", "dor"],
    safetyNote: "Não aplicar em pele lesionada, mucosas ou olhos. Siga a orientação do farmacêutico."
  },
  {
    name: "Salonpas Gel 35g",
    aliases: ["salonpas gel", "salompas gel", "gel salonpas"],
    price: 24.50,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 35g",
    unitName: "bisnaga",
    activeIngredient: "Metil Salicilato + Mentol",
    manufacturer: "Hisamitsu",
    isGeneric: false,
    recipeType: "none",
    tags: ["topico", "muscular", "gel", "dor"],
    safetyNote: "Uso externo. Não ingerir. Consulte o farmacêutico."
  },
  {
    name: "Gelol Creme 60g",
    aliases: ["gelol", "gelol creme", "creme gelol"],
    price: 14.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 60g",
    unitName: "bisnaga",
    activeIngredient: "Mentol + Metil Salicilato + Cânfora",
    manufacturer: "EMS",
    isGeneric: false,
    recipeType: "none",
    tags: ["topico", "muscular", "creme"],
    safetyNote: "Uso externo. Consulte o farmacêutico."
  },
  {
    name: "Bengay Creme Analgésico 50g",
    aliases: ["bengay", "bengay creme", "creme bengay"],
    price: 22.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 50g",
    unitName: "bisnaga",
    activeIngredient: "Mentol + Metil Salicilato",
    manufacturer: "Kenvue (J&J)",
    isGeneric: false,
    recipeType: "none",
    tags: ["topico", "muscular", "creme"],
    safetyNote: "Uso externo. Não aplicar em feridas abertas."
  },
  {
    name: "Voltaren Emulgel 50g",
    aliases: ["voltaren", "voltaren emulgel", "voltaren gel", "diclofenaco gel voltaren"],
    price: 34.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 50g",
    unitName: "bisnaga",
    activeIngredient: "Diclofenaco Dietilamônio",
    manufacturer: "Novartis",
    isGeneric: false,
    recipeType: "none",
    tags: ["topico", "anti-inflamatorio", "gel"],
    safetyNote: "Uso externo. Consulte médico ou farmacêutico."
  },
  {
    name: "Diclofenaco Gel 1% 60g Genérico",
    aliases: ["diclofenaco gel", "gel diclofenaco", "diclofenaco topico"],
    price: 12.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 60g",
    unitName: "bisnaga",
    activeIngredient: "Diclofenaco Dietilamônio",
    manufacturer: "EMS",
    isGeneric: true,
    recipeType: "none",
    tags: ["topico", "generico", "gel"],
    safetyNote: "Uso externo. Consulte o farmacêutico."
  },
  {
    name: "Deep Heat Spray 150ml",
    aliases: ["deep heat", "deep heat spray"],
    price: 28.50,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Spray de 150ml",
    unitName: "frasco",
    activeIngredient: "Metil Salicilato + Mentol",
    manufacturer: "Reckitt",
    isGeneric: false,
    recipeType: "none",
    tags: ["topico", "muscular", "spray"],
    safetyNote: "Inflamável. Não usar perto de chamas. Uso externo."
  },
  {
    name: "Cataflan Emulgel 45g",
    aliases: ["cataflan emulgel", "cataflam gel", "cataflan gel"],
    price: 42.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 45g",
    unitName: "bisnaga",
    activeIngredient: "Diclofenaco de Potássio",
    manufacturer: "Novartis",
    isGeneric: false,
    recipeType: "none",
    tags: ["topico", "anti-inflamatorio"],
    safetyNote: "Uso externo. Consulte médico ou farmacêutico."
  },
  {
    name: "Salvia Spray Bucal 30ml",
    aliases: ["salvia spray", "spray bucal salvia"],
    price: 18.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco spray de 30ml",
    unitName: "frasco",
    activeIngredient: "Extrato de Sálvia",
    manufacturer: "Daudt",
    isGeneric: false,
    recipeType: "none",
    tags: ["bucal", "topico"],
    safetyNote: "Consulte o farmacêutico."
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // HIGIENE PESSOAL — DESODORANTES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Desodorante Rexona Sem Perfume Roll-On 50ml",
    aliases: ["rexona", "desodorante rexona", "rexona roll-on", "rexona sem perfume"],
    price: 12.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco roll-on de 50ml",
    unitName: "frasco",
    activeIngredient: "Cloreto de Alumínio",
    manufacturer: "Unilever",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "desodorante"],
    safetyNote: "Não usar em pele irritada ou recém-depilada."
  },
  {
    name: "Desodorante Dove Sem Perfume Antitranspirante 150ml",
    aliases: ["dove desodorante", "desodorante dove", "dove spray"],
    price: 14.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Aerossol de 150ml",
    unitName: "frasco",
    activeIngredient: "Clorohidrato de Alumínio",
    manufacturer: "Unilever",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "desodorante"],
    safetyNote: "Uso externo. Não inalar. Inflamável."
  },
  {
    name: "Desodorante Old Spice Original 150ml",
    aliases: ["old spice", "desodorante old spice"],
    price: 11.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Aerossol de 150ml",
    unitName: "frasco",
    activeIngredient: "Clorohidrato de Alumínio",
    manufacturer: "P&G",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "desodorante", "masculino"],
    safetyNote: "Inflamável. Não usar perto de chamas."
  },
  {
    name: "Desodorante Feminino Nivea Black & White 150ml",
    aliases: ["nivea desodorante", "desodorante nivea", "nivea black white"],
    price: 13.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Aerossol de 150ml",
    unitName: "frasco",
    activeIngredient: "Clorohidrato de Alumínio",
    manufacturer: "Beiersdorf",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "desodorante", "feminino"],
    safetyNote: "Uso externo."
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // HIGIENE PESSOAL — SHAMPOOS E CONDICIONADORES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Shampoo Head & Shoulders Anticaspa 200ml",
    aliases: ["head shoulders", "head & shoulders", "shampoo head shoulders", "shampoo anticaspa head"],
    price: 18.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 200ml",
    unitName: "frasco",
    activeIngredient: "Piritionato de Zinco",
    manufacturer: "P&G",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "shampoo", "cabelo", "anticaspa"],
    safetyNote: "Evitar contato com os olhos."
  },
  {
    name: "Shampoo Pantene Hidratação 400ml",
    aliases: ["pantene shampoo", "shampoo pantene"],
    price: 22.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 400ml",
    unitName: "frasco",
    activeIngredient: "Pro-Vitamina B5",
    manufacturer: "P&G",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "shampoo", "cabelo"],
    safetyNote: "Evitar contato com os olhos."
  },
  {
    name: "Shampoo Elseve Reparação Total 5 400ml",
    aliases: ["elseve shampoo", "shampoo elseve", "shampoo loreal elseve"],
    price: 21.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 400ml",
    unitName: "frasco",
    activeIngredient: "Ceramidas + Proteínas",
    manufacturer: "L'Oréal",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "shampoo", "cabelo"],
    safetyNote: "Evitar contato com os olhos."
  },
  {
    name: "Shampoo Selsun Blue Anticaspa 200ml",
    aliases: ["selsun blue", "shampoo selsun", "selsun"],
    price: 26.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 200ml",
    unitName: "frasco",
    activeIngredient: "Sulfeto de Selênio 2,5%",
    manufacturer: "Abbott",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "shampoo", "anticaspa", "dermocosmetico"],
    safetyNote: "Evitar contato com os olhos. Consulte dermatologista se persistir."
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // HIGIENE PESSOAL — SABONETES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Sabonete Líquido Protex Antibacteriano 250ml",
    aliases: ["sabonete protex", "protex liquido", "sabonete liquido protex"],
    price: 9.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 250ml",
    unitName: "frasco",
    activeIngredient: "Triclosano",
    manufacturer: "Colgate-Palmolive",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "sabonete"],
    safetyNote: "Uso externo."
  },
  {
    name: "Sabonete Dove Hidratante Original 90g",
    aliases: ["sabonete dove", "dove sabonete"],
    price: 4.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Barra de 90g",
    unitName: "unidade",
    activeIngredient: "1/4 de Creme Hidratante",
    manufacturer: "Unilever",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "sabonete"],
    safetyNote: "Uso externo."
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // HIGIENE PESSOAL — ABSORVENTES E ÍNTIMOS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Absorvente Always Noite com Abas 8 unidades",
    aliases: ["absorvente always", "always noite", "always com abas"],
    price: 8.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Pacote com 8 unidades",
    unitName: "pacote",
    activeIngredient: "",
    manufacturer: "P&G",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "feminino", "absorvente"],
    safetyNote: "Trocar a cada 4-6 horas. Consulte ginecologista se necessário."
  },
  {
    name: "Absorvente Intimus Days 15 unidades",
    aliases: ["absorvente intimus", "intimus days", "intimus"],
    price: 7.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Pacote com 15 unidades",
    unitName: "pacote",
    activeIngredient: "",
    manufacturer: "Kimberly-Clark",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "feminino", "absorvente"],
    safetyNote: "Consulte ginecologista se necessário."
  },
  {
    name: "Sabonete Íntimo Lactacyd 200ml",
    aliases: ["lactacyd", "sabonete intimo lactacyd", "higiene intima lactacyd"],
    price: 24.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 200ml",
    unitName: "frasco",
    activeIngredient: "Ácido Lático + Lactoserum",
    manufacturer: "Omega Pharma",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "feminino", "intimo"],
    safetyNote: "Uso externo. Consulte ginecologista."
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DERMOCOSMÉTICOS — HIDRATANTES E CICATRIZANTES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Bepantol Derma Loção Hidratante 200ml",
    aliases: ["bepantol loção", "bepantol hidratante", "bepantol derma loção", "bepantol 200ml"],
    price: 34.90,
    category: "Dermocosmetico",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 200ml",
    unitName: "frasco",
    activeIngredient: "Dexpantenol (Pró-vitamina B5)",
    manufacturer: "Bayer",
    isGeneric: false,
    recipeType: "none",
    tags: ["dermocosmetico", "hidratante", "bepantol"],
    safetyNote: "Uso externo. Consulte médico se houver reação alérgica."
  },
  {
    name: "Bepantol Derma Creme 30g",
    aliases: ["bepantol creme", "bepantol derma creme", "bepantol 30g"],
    price: 22.90,
    category: "Dermocosmetico",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 30g",
    unitName: "bisnaga",
    activeIngredient: "Dexpantenol 5%",
    manufacturer: "Bayer",
    isGeneric: false,
    recipeType: "none",
    tags: ["dermocosmetico", "cicatrizante"],
    safetyNote: "Uso externo."
  },
  {
    name: "Bepantol Baby Pomada 30g",
    aliases: ["bepantol baby", "bepantol pomada", "pomada bepantol", "bepantol assadura"],
    price: 24.90,
    category: "Bebe",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 30g",
    unitName: "bisnaga",
    activeIngredient: "Dexpantenol 5%",
    manufacturer: "Bayer",
    isGeneric: false,
    recipeType: "none",
    tags: ["bebe", "assadura", "cicatrizante"],
    safetyNote: "Uso externo em bebês. Consulte pediatra se persistir."
  },
  {
    name: "Hipoglós Pomada 60g",
    aliases: ["hipoglós", "hiposol", "pomada hiposol", "hipoglos"],
    price: 19.90,
    category: "Bebe",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 60g",
    unitName: "bisnaga",
    activeIngredient: "Óxido de Zinco + Vitamina A + D",
    manufacturer: "Kenvue",
    isGeneric: false,
    recipeType: "none",
    tags: ["bebe", "assadura", "cicatrizante"],
    safetyNote: "Uso externo. Consulte pediatra."
  },
  {
    name: "Cicatricure Creme Anti-marcas 30g",
    aliases: ["cicatricure", "creme cicatricure", "cicatricure anti-marcas"],
    price: 39.90,
    category: "Dermocosmetico",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 30g",
    unitName: "bisnaga",
    activeIngredient: "Alantoína + Vitamina E + Ácido Glicólico",
    manufacturer: "Genomma Lab",
    isGeneric: false,
    recipeType: "none",
    tags: ["dermocosmetico", "cicatrizante"],
    safetyNote: "Uso externo. Evitar exposição solar após aplicação."
  },
  {
    name: "Contratubex Gel 20g",
    aliases: ["contratubex", "gel contratubex", "contratubex cicatriz"],
    price: 54.90,
    category: "Dermocosmetico",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 20g",
    unitName: "bisnaga",
    activeIngredient: "Heparina + Cebola + Alantoína",
    manufacturer: "Merz Pharma",
    isGeneric: false,
    recipeType: "none",
    tags: ["dermocosmetico", "cicatriz"],
    safetyNote: "Uso externo. Consulte dermatologista."
  },
  {
    name: "Calamine Loção 120ml",
    aliases: ["calamine", "loção calamine", "calamyn"],
    price: 14.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 120ml",
    unitName: "frasco",
    activeIngredient: "Calamine + Óxido de Zinco",
    manufacturer: "Cimed",
    isGeneric: false,
    recipeType: "none",
    tags: ["dermocosmetico", "topico", "coceira"],
    safetyNote: "Uso externo. Agitar antes de usar."
  },
  {
    name: "Fenistil Gel 1mg/g 30g",
    aliases: ["fenistil gel", "fenistil", "gel fenistil", "dimetindeno gel"],
    price: 32.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 30g",
    unitName: "bisnaga",
    activeIngredient: "Maleato de Dimetindeno",
    manufacturer: "Novartis",
    isGeneric: false,
    recipeType: "none",
    tags: ["topico", "anti-alergico", "coceira"],
    safetyNote: "Uso externo. Evitar olhos. Consulte médico se necessário."
  },
  {
    name: "Nivea Creme Original Lata 400ml",
    aliases: ["nivea creme", "creme nivea", "nivea original"],
    price: 26.90,
    category: "Dermocosmetico",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Lata de 400ml",
    unitName: "lata",
    activeIngredient: "Eucerit + Glicerina",
    manufacturer: "Beiersdorf",
    isGeneric: false,
    recipeType: "none",
    tags: ["dermocosmetico", "hidratante"],
    safetyNote: "Uso externo."
  },
  {
    name: "Eucerin pH5 Loção Hidratante 400ml",
    aliases: ["eucerin", "eucerin ph5", "loção eucerin"],
    price: 69.90,
    category: "Dermocosmetico",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 400ml",
    unitName: "frasco",
    activeIngredient: "Ácido Lático + Glicerina",
    manufacturer: "Beiersdorf",
    isGeneric: false,
    recipeType: "none",
    tags: ["dermocosmetico", "hidratante"],
    safetyNote: "Uso externo. Testado dermatologicamente."
  },
  {
    name: "CeraVe Loção Hidratante 237ml",
    aliases: ["cerave", "cerave loção", "loção cerave"],
    price: 79.90,
    category: "Dermocosmetico",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 237ml",
    unitName: "frasco",
    activeIngredient: "Ceramidas + Ácido Hialurônico",
    manufacturer: "L'Oréal",
    isGeneric: false,
    recipeType: "none",
    tags: ["dermocosmetico", "hidratante"],
    safetyNote: "Uso externo. Testado dermatologicamente."
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PROTETOR SOLAR
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Protetor Solar Sundown FPS 30 200ml",
    aliases: ["sundown fps 30", "sundown 30", "protetor solar sundown"],
    price: 42.90,
    category: "Dermocosmetico",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 200ml",
    unitName: "frasco",
    activeIngredient: "Octinoxato + Octocrileno + Benzofenona-3",
    manufacturer: "Kenvue",
    isGeneric: false,
    recipeType: "none",
    tags: ["dermocosmetico", "protetor solar"],
    safetyNote: "Reaplicar a cada 2h de exposição solar."
  },
  {
    name: "Protetor Solar Sundown FPS 60 200ml",
    aliases: ["sundown fps 60", "sundown 60", "sundown fps60"],
    price: 52.90,
    category: "Dermocosmetico",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 200ml",
    unitName: "frasco",
    activeIngredient: "Octinoxato + Octocrileno + Avobenzona",
    manufacturer: "Kenvue",
    isGeneric: false,
    recipeType: "none",
    tags: ["dermocosmetico", "protetor solar"],
    safetyNote: "Reaplicar a cada 2h de exposição solar."
  },
  {
    name: "Protetor Solar La Roche-Posay Anthelios XL FPS 50+ 300ml",
    aliases: ["la roche posay anthelios", "anthelios fps 50", "protetor solar la roche"],
    price: 149.90,
    category: "Dermocosmetico",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 300ml",
    unitName: "frasco",
    activeIngredient: "Mexoryl SX + XL",
    manufacturer: "L'Oréal",
    isGeneric: false,
    recipeType: "none",
    tags: ["dermocosmetico", "protetor solar"],
    safetyNote: "Reaplicar a cada 2h. Testado dermatologicamente."
  },
  {
    name: "Protetor Solar Neutrogena Sun Fresh FPS 70 200ml",
    aliases: ["neutrogena sun fresh", "protetor neutrogena", "neutrogena fps 70"],
    price: 58.90,
    category: "Dermocosmetico",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 200ml",
    unitName: "frasco",
    activeIngredient: "Homosalato + Octocrileno + Avobenzona",
    manufacturer: "Kenvue",
    isGeneric: false,
    recipeType: "none",
    tags: ["dermocosmetico", "protetor solar"],
    safetyNote: "Reaplicar a cada 2h de exposição."
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SUPLEMENTOS E VITAMINAS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Vitamina C 1g EMS 30 comprimidos",
    aliases: ["vitamina c 1g", "vitamina c ems", "vitamina c efervescente", "vit c"],
    price: 18.90,
    category: "Suplemento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Caixa com 30 comprimidos",
    unitName: "caixa",
    activeIngredient: "Ácido Ascórbico 1000mg",
    manufacturer: "EMS",
    isGeneric: false,
    recipeType: "none",
    tags: ["suplemento", "vitamina"],
    safetyNote: "Consulte médico antes de suplementar."
  },
  {
    name: "Vitamina D3 2000UI 60 cápsulas",
    aliases: ["vitamina d 2000", "vitamina d3 2000", "vit d 2000ui", "vitamina d"],
    price: 29.90,
    category: "Suplemento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco com 60 cápsulas",
    unitName: "frasco",
    activeIngredient: "Colecalciferol 2000UI",
    manufacturer: "EMS",
    isGeneric: false,
    recipeType: "none",
    tags: ["suplemento", "vitamina"],
    safetyNote: "Consulte médico para dosagem adequada."
  },
  {
    name: "Vitamina D3 5000UI 60 cápsulas",
    aliases: ["vitamina d 5000", "vitamina d3 5000", "vit d 5000ui"],
    price: 39.90,
    category: "Suplemento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco com 60 cápsulas",
    unitName: "frasco",
    activeIngredient: "Colecalciferol 5000UI",
    manufacturer: "Cimed",
    isGeneric: false,
    recipeType: "none",
    tags: ["suplemento", "vitamina"],
    safetyNote: "Doses elevadas requerem orientação médica."
  },
  {
    name: "Complexo B 60 comprimidos",
    aliases: ["complexo b", "vitaminas do complexo b", "vit complexo b"],
    price: 14.90,
    category: "Suplemento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco com 60 comprimidos",
    unitName: "frasco",
    activeIngredient: "B1 + B2 + B3 + B5 + B6 + B12",
    manufacturer: "EMS",
    isGeneric: false,
    recipeType: "none",
    tags: ["suplemento", "vitamina"],
    safetyNote: "Consulte médico antes de suplementar."
  },
  {
    name: "Ômega 3 1g 60 cápsulas",
    aliases: ["omega 3", "ômega 3", "oleo de peixe", "omega3"],
    price: 24.90,
    category: "Suplemento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco com 60 cápsulas",
    unitName: "frasco",
    activeIngredient: "Ácidos Graxos Ômega-3 (EPA + DHA)",
    manufacturer: "EMS",
    isGeneric: false,
    recipeType: "none",
    tags: ["suplemento", "omega"],
    safetyNote: "Consulte médico antes de suplementar."
  },
  {
    name: "Colágeno Hidrolisado 300g",
    aliases: ["colágeno", "colageno hidrolisado", "colageno em pó"],
    price: 49.90,
    category: "Suplemento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Pote de 300g",
    unitName: "pote",
    activeIngredient: "Colágeno Hidrolisado",
    manufacturer: "Vitafor",
    isGeneric: false,
    recipeType: "none",
    tags: ["suplemento", "colageno"],
    safetyNote: "Consulte nutricionista ou médico."
  },
  {
    name: "Centrum Multivitamínico 30 comprimidos",
    aliases: ["centrum", "multivitaminico centrum", "polivitaminico centrum"],
    price: 49.90,
    category: "Suplemento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Caixa com 30 comprimidos",
    unitName: "caixa",
    activeIngredient: "Multivitamínico completo",
    manufacturer: "Pfizer",
    isGeneric: false,
    recipeType: "none",
    tags: ["suplemento", "vitamina", "polivitaminico"],
    safetyNote: "Consulte médico antes de suplementar."
  },
  {
    name: "Zinco 30mg 60 cápsulas",
    aliases: ["zinco", "suplemento zinco", "zinco 30mg"],
    price: 19.90,
    category: "Suplemento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco com 60 cápsulas",
    unitName: "frasco",
    activeIngredient: "Zinco Quelato 30mg",
    manufacturer: "EMS",
    isGeneric: false,
    recipeType: "none",
    tags: ["suplemento", "mineral"],
    safetyNote: "Não exceder a dose recomendada."
  },
  {
    name: "Sulfato Ferroso 40mg 30 comprimidos",
    aliases: ["sulfato ferroso", "ferro 40mg", "suplemento de ferro", "ferro ferroso"],
    price: 8.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Caixa com 30 comprimidos",
    unitName: "caixa",
    activeIngredient: "Sulfato Ferroso 40mg",
    manufacturer: "Cimed",
    isGeneric: true,
    recipeType: "none",
    tags: ["suplemento", "mineral", "ferro"],
    safetyNote: "Tomar preferencialmente com vitamina C. Pode escurecer as fezes."
  },
  {
    name: "Biotina 60mcg 60 cápsulas",
    aliases: ["biotina", "biotina 60mcg", "vitamina biotina"],
    price: 34.90,
    category: "Suplemento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco com 60 cápsulas",
    unitName: "frasco",
    activeIngredient: "Biotina (Vitamina B7) 60mcg",
    manufacturer: "Vitafor",
    isGeneric: false,
    recipeType: "none",
    tags: ["suplemento", "vitamina", "cabelo", "unha"],
    safetyNote: "Consulte médico antes de suplementar."
  },
  {
    name: "Magnesio Quelato 350mg 60 cápsulas",
    aliases: ["magnesio", "magnésio quelato", "magnesio 350"],
    price: 39.90,
    category: "Suplemento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco com 60 cápsulas",
    unitName: "frasco",
    activeIngredient: "Bisglicinato de Magnésio 350mg",
    manufacturer: "EMS",
    isGeneric: false,
    recipeType: "none",
    tags: ["suplemento", "mineral"],
    safetyNote: "Consulte médico antes de suplementar."
  },
  {
    name: "Cálcio + Vitamina D 60 comprimidos",
    aliases: ["calcio vitamina d", "cálcio + d", "calcio com vit d", "calcio d"],
    price: 24.90,
    category: "Suplemento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco com 60 comprimidos",
    unitName: "frasco",
    activeIngredient: "Carbonato de Cálcio + Colecalciferol",
    manufacturer: "Cimed",
    isGeneric: false,
    recipeType: "none",
    tags: ["suplemento", "mineral", "vitamina"],
    safetyNote: "Consulte médico antes de suplementar."
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BEBÊ E CRIANÇA
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Fralda Pampers Supersec RN 28 unidades",
    aliases: ["fralda pampers rn", "pampers rn", "fralda pampers recem nascido", "pampers"],
    price: 39.90,
    category: "Bebe",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Pacote com 28 unidades",
    unitName: "pacote",
    activeIngredient: "",
    manufacturer: "P&G",
    isGeneric: false,
    recipeType: "none",
    tags: ["bebe", "fralda"],
    safetyNote: "Verificar tamanho adequado ao bebê. Trocar regularmente."
  },
  {
    name: "Fralda Huggies Supreme Care P 32 unidades",
    aliases: ["fralda huggies", "huggies p", "huggies supreme", "huggies"],
    price: 44.90,
    category: "Bebe",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Pacote com 32 unidades",
    unitName: "pacote",
    activeIngredient: "",
    manufacturer: "Kimberly-Clark",
    isGeneric: false,
    recipeType: "none",
    tags: ["bebe", "fralda"],
    safetyNote: "Trocar regularmente para prevenir assaduras."
  },
  {
    name: "Shampoo Johnson's Baby Regular 200ml",
    aliases: ["shampoo johnsons", "johnsons baby shampoo", "shampoo bebe johnsons"],
    price: 14.90,
    category: "Bebe",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 200ml",
    unitName: "frasco",
    activeIngredient: "",
    manufacturer: "Kenvue",
    isGeneric: false,
    recipeType: "none",
    tags: ["bebe", "shampoo"],
    safetyNote: "Fórmula não irrita os olhos. Uso em bebês e crianças."
  },
  {
    name: "Sabonete Líquido Johnson's Baby 200ml",
    aliases: ["sabonete johnsons baby", "johnsons baby sabonete", "sabonete bebe johnsons"],
    price: 12.90,
    category: "Bebe",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 200ml",
    unitName: "frasco",
    activeIngredient: "",
    manufacturer: "Kenvue",
    isGeneric: false,
    recipeType: "none",
    tags: ["bebe", "sabonete"],
    safetyNote: "Testado dermatologicamente. Hipoalergênico."
  },
  {
    name: "Lenços Umedecidos Pampers 96 unidades",
    aliases: ["lenços umedecidos pampers", "lenco umedecido pampers", "pampers lenços"],
    price: 18.90,
    category: "Bebe",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Pacote com 96 unidades",
    unitName: "pacote",
    activeIngredient: "",
    manufacturer: "P&G",
    isGeneric: false,
    recipeType: "none",
    tags: ["bebe", "higiene"],
    safetyNote: "Hipoalergênico. Testado dermatologicamente."
  },
  {
    name: "Termômetro Digital Omron MC-246",
    aliases: ["termometro digital", "termometro omron", "termômetro digital omron"],
    price: 49.90,
    category: "Equipamento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "1 unidade",
    unitName: "unidade",
    activeIngredient: "",
    manufacturer: "Omron",
    isGeneric: false,
    recipeType: "none",
    tags: ["equipamento", "termometro"],
    safetyNote: "Consulte manual de instrução. Não substitui avaliação médica."
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SAÚDE SEXUAL
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Preservativo Jontex Lubrificado 6 unidades",
    aliases: ["preservativo jontex", "jontex lubrificado", "camisinha jontex", "jontex"],
    price: 12.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Caixa com 6 unidades",
    unitName: "caixa",
    activeIngredient: "",
    manufacturer: "SSL International",
    isGeneric: false,
    recipeType: "none",
    tags: ["saude sexual", "preservativo"],
    safetyNote: "Verificar data de validade. Preservar em local fresco."
  },
  {
    name: "Preservativo Prudence Classic 12 unidades",
    aliases: ["preservativo prudence", "prudence classic", "camisinha prudence", "prudence"],
    price: 18.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Caixa com 12 unidades",
    unitName: "caixa",
    activeIngredient: "",
    manufacturer: "Reckitt",
    isGeneric: false,
    recipeType: "none",
    tags: ["saude sexual", "preservativo"],
    safetyNote: "Verificar data de validade. Preservar em local fresco."
  },
  {
    name: "Lubrificante KY Gel 50g",
    aliases: ["ky gel", "lubrificante ky", "gel ky", "gel lubrificante ky"],
    price: 19.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 50g",
    unitName: "bisnaga",
    activeIngredient: "Glicerina + Hidroxietilcelulose",
    manufacturer: "Kenvue",
    isGeneric: false,
    recipeType: "none",
    tags: ["saude sexual", "lubrificante"],
    safetyNote: "Uso externo. Compatível com preservativos."
  },
  {
    name: "Teste de Gravidez DUO 2 unidades",
    aliases: ["teste de gravidez", "teste gravidez", "teste gravidez duo", "pregnancy test"],
    price: 22.90,
    category: "Equipamento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Caixa com 2 testes",
    unitName: "caixa",
    activeIngredient: "",
    manufacturer: "Pérola",
    isGeneric: false,
    recipeType: "none",
    tags: ["saude sexual", "teste"],
    safetyNote: "Consulte médico para confirmação."
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PRIMEIROS SOCORROS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Curativo Band-Aid Classic 10 unidades",
    aliases: ["band aid", "band-aid", "curativo band aid", "curativo adesivo"],
    price: 6.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Caixa com 10 unidades",
    unitName: "caixa",
    activeIngredient: "",
    manufacturer: "Kenvue",
    isGeneric: false,
    recipeType: "none",
    tags: ["primeiros socorros", "curativo"],
    safetyNote: "Trocar diariamente. Consulte médico em casos graves."
  },
  {
    name: "Álcool Gel 70% Antisséptico 420g",
    aliases: ["alcool gel", "álcool gel 70", "gel 70", "alcool em gel", "antiseptico gel"],
    price: 8.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 420g",
    unitName: "frasco",
    activeIngredient: "Etanol 70%",
    manufacturer: "Farmax",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "antiseptico", "alcool"],
    safetyNote: "Inflamável. Evitar contato com os olhos. Não ingerir."
  },
  {
    name: "Água Oxigenada 10V 100ml",
    aliases: ["agua oxigenada", "água oxigenada 10v", "peroxido hidrogenio", "h2o2"],
    price: 4.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 100ml",
    unitName: "frasco",
    activeIngredient: "Peróxido de Hidrogênio 3%",
    manufacturer: "Cimed",
    isGeneric: true,
    recipeType: "none",
    tags: ["primeiros socorros", "antisseptico"],
    safetyNote: "Uso externo. Não aplicar em feridas profundas."
  },
  {
    name: "Atadura Crepon 15cm x 1,6m 12 unidades",
    aliases: ["atadura crepon", "atadura", "crepon 15cm"],
    price: 12.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Pacote com 12 unidades",
    unitName: "pacote",
    activeIngredient: "",
    manufacturer: "Cremer",
    isGeneric: false,
    recipeType: "none",
    tags: ["primeiros socorros", "curativo"],
    safetyNote: "Não apertar em excesso para não comprometer circulação."
  },
  {
    name: "Esparadrapo Bege 2,5cm x 4,5m",
    aliases: ["esparadrapo", "esparadrapo bege"],
    price: 5.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Rolo 2,5cm x 4,5m",
    unitName: "rolo",
    activeIngredient: "",
    manufacturer: "Cremer",
    isGeneric: false,
    recipeType: "none",
    tags: ["primeiros socorros", "curativo"],
    safetyNote: "Uso externo."
  },
  {
    name: "Algodão Hidrófilo Johnson's 50g",
    aliases: ["algodão", "algodao hidrofilo", "algodão johnsons"],
    price: 4.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Rolo de 50g",
    unitName: "rolo",
    activeIngredient: "",
    manufacturer: "Kenvue",
    isGeneric: false,
    recipeType: "none",
    tags: ["primeiros socorros"],
    safetyNote: "Uso externo."
  },
  {
    name: "Seringa Descartável BD 3ml com Agulha 25x7",
    aliases: ["seringa bd", "seringa 3ml", "seringa descartavel"],
    price: 2.50,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "1 unidade",
    unitName: "unidade",
    activeIngredient: "",
    manufacturer: "BD",
    isGeneric: false,
    recipeType: "none",
    tags: ["equipamento", "seringa"],
    safetyNote: "Descartável. Não reutilizar."
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ANTIFÚNGICOS TÓPICOS ADICIONAIS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Canesten Creme 1% 30g",
    aliases: ["canesten", "canesten creme", "clotrimazol creme canesten"],
    price: 32.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 30g",
    unitName: "bisnaga",
    activeIngredient: "Clotrimazol 1%",
    manufacturer: "Bayer",
    isGeneric: false,
    recipeType: "none",
    tags: ["antifungico", "topico"],
    safetyNote: "Uso externo. Consulte médico se não melhorar em 4 semanas."
  },
  {
    name: "Daktarin Creme 2% 30g",
    aliases: ["daktarin", "daktarin creme", "miconazol creme daktarin"],
    price: 29.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 30g",
    unitName: "bisnaga",
    activeIngredient: "Miconazol Nitrato 2%",
    manufacturer: "Janssen-Cilag",
    isGeneric: false,
    recipeType: "none",
    tags: ["antifungico", "topico"],
    safetyNote: "Uso externo. Consulte médico ou farmacêutico."
  },
  {
    name: "Clotrimazol Creme 1% 30g Genérico",
    aliases: ["clotrimazol creme", "creme clotrimazol", "clotrimazol generico"],
    price: 12.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 30g",
    unitName: "bisnaga",
    activeIngredient: "Clotrimazol 1%",
    manufacturer: "EMS",
    isGeneric: true,
    recipeType: "none",
    tags: ["antifungico", "topico", "generico"],
    safetyNote: "Uso externo."
  },
  {
    name: "Sempre Livre Creme Antifúngico 30g",
    aliases: ["sempre livre creme", "nistatina creme", "antifungico nistatina"],
    price: 24.90,
    category: "MIP",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 30g",
    unitName: "bisnaga",
    activeIngredient: "Nistatina",
    manufacturer: "Cimed",
    isGeneric: false,
    recipeType: "none",
    tags: ["antifungico", "topico"],
    safetyNote: "Uso externo. Consulte médico."
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CUIDADOS BUCAIS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Creme Dental Colgate Total 12 90g",
    aliases: ["colgate total 12", "pasta colgate", "creme dental colgate"],
    price: 7.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 90g",
    unitName: "bisnaga",
    activeIngredient: "Fluoreto de Sódio + Triclosan",
    manufacturer: "Colgate-Palmolive",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "bucal"],
    safetyNote: "Não engolir. Fora do alcance de crianças menores de 3 anos."
  },
  {
    name: "Creme Dental Sensodyne Reparação e Proteção 90g",
    aliases: ["sensodyne", "pasta sensodyne", "creme dental sensodyne"],
    price: 16.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Bisnaga de 90g",
    unitName: "bisnaga",
    activeIngredient: "Nitrato de Potássio + Fluoreto",
    manufacturer: "Haleon",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "bucal", "sensibilidade"],
    safetyNote: "Não engolir. Para sensibilidade dentária."
  },
  {
    name: "Enxaguante Bucal Listerine Cool Mint 500ml",
    aliases: ["listerine", "enxaguante listerine", "listerine cool mint"],
    price: 18.90,
    category: "Higiene",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Frasco de 500ml",
    unitName: "frasco",
    activeIngredient: "Timol + Eucaliptol + Mentol",
    manufacturer: "Kenvue",
    isGeneric: false,
    recipeType: "none",
    tags: ["higiene", "bucal"],
    safetyNote: "Não engolir. Não usar em crianças menores de 12 anos."
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // EQUIPAMENTOS E MEDIDORES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Medidor de Pressão Digital de Pulso Omron HEM-6161",
    aliases: ["medidor de pressão", "aparelho de pressão", "esfigmomanômetro digital", "medidor pressao omron"],
    price: 149.90,
    category: "Equipamento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "1 unidade",
    unitName: "unidade",
    activeIngredient: "",
    manufacturer: "Omron",
    isGeneric: false,
    recipeType: "none",
    tags: ["equipamento", "pressao", "cardiologia"],
    safetyNote: "Consulte manual. Não substitui avaliação médica."
  },
  {
    name: "Glicosímetro Accu-Chek Active Kit Completo",
    aliases: ["glicosimetro accu chek", "medidor de glicose", "accu chek active", "glicose accu chek"],
    price: 89.90,
    category: "Equipamento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Kit completo",
    unitName: "kit",
    activeIngredient: "",
    manufacturer: "Roche",
    isGeneric: false,
    recipeType: "none",
    tags: ["equipamento", "diabetes", "glicose"],
    safetyNote: "Consulte médico para interpretação dos resultados."
  },
  {
    name: "Fitas para Glicosímetro Accu-Chek Active 25 unidades",
    aliases: ["fitas accu chek", "tiras glicosimetro", "fitas para glicose accu chek"],
    price: 39.90,
    category: "Equipamento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "Caixa com 25 fitas",
    unitName: "caixa",
    activeIngredient: "",
    manufacturer: "Roche",
    isGeneric: false,
    recipeType: "none",
    tags: ["equipamento", "diabetes"],
    safetyNote: "Verificar compatibilidade com o glicosímetro."
  },
  {
    name: "Nebulizador Inalador Omron NE-C801",
    aliases: ["nebulizador omron", "inalador omron", "nebulizador", "inalador"],
    price: 249.90,
    category: "Equipamento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "1 unidade",
    unitName: "unidade",
    activeIngredient: "",
    manufacturer: "Omron",
    isGeneric: false,
    recipeType: "none",
    tags: ["equipamento", "respiratorio"],
    safetyNote: "Consulte médico. Não usar sem orientação profissional."
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ORTOPÉDICOS / POSTURAIS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Joelheira Ortopédica Tamanho M",
    aliases: ["joelheira ortopedica", "joelheira", "suporte joelho"],
    price: 39.90,
    category: "Equipamento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "1 unidade tamanho M",
    unitName: "unidade",
    activeIngredient: "",
    manufacturer: "Coxinha",
    isGeneric: false,
    recipeType: "none",
    tags: ["equipamento", "ortopedico"],
    safetyNote: "Consulte médico ou fisioterapeuta."
  },
  {
    name: "Tornozeleira Ortopédica Tamanho M",
    aliases: ["tornozeleira", "tornozeleira ortopedica", "suporte tornozelo"],
    price: 34.90,
    category: "Equipamento",
    needsRecipe: false,
    allowsDelivery: true,
    presentation: "1 unidade tamanho M",
    unitName: "unidade",
    activeIngredient: "",
    manufacturer: "Coxinha",
    isGeneric: false,
    recipeType: "none",
    tags: ["equipamento", "ortopedico"],
    safetyNote: "Consulte médico ou fisioterapeuta."
  },
];

if (typeof module !== 'undefined') module.exports = ENRICHMENT_DB;
