-- Script de criação e população da tabela de medicamentos para AtendClinical (Farmácia)

CREATE TABLE IF NOT EXISTS public.farmacia_medicamentos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    aliases TEXT[],
    preco NUMERIC(10, 2) NOT NULL,
    categoria TEXT NOT NULL,
    precisa_receita BOOLEAN NOT NULL DEFAULT false,
    tipo_receita TEXT, -- 'simples', 'retida', 'azul', 'especial'
    permite_delivery BOOLEAN NOT NULL DEFAULT true,
    apresentacao TEXT,
    unidade_medida TEXT,
    principio_ativo TEXT,
    indicacao TEXT,
    posologia TEXT,
    contraindicacoes TEXT,
    fabricante TEXT,
    eh_generico BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.farmacia_medicamentos ENABLE ROW LEVEL SECURITY;

-- Criar política de leitura pública (anon e authenticated)
DROP POLICY IF EXISTS "Permitir leitura pública de medicamentos" ON public.farmacia_medicamentos;
CREATE POLICY "Permitir leitura pública de medicamentos" 
ON public.farmacia_medicamentos 
FOR SELECT 
USING (true);

-- Limpar dados anteriores se existirem (para evitar duplicados no seed)
TRUNCATE TABLE public.farmacia_medicamentos CASCADE;

-- Inserção de sementes (MIPs, Tarjas Vermelhas, Antibióticos, Tarjas Pretas, Especiais)
INSERT INTO public.farmacia_medicamentos 
(nome, aliases, preco, categoria, precisa_receita, tipo_receita, permite_delivery, apresentacao, unidade_medida, principio_ativo, indicacao, posologia, contraindicacoes, fabricante, eh_generico)
VALUES
('Dipirona Gotas', ARRAY['dipirona', 'dipirona gotas', 'dipirona liquida', 'novalgina'], 12.90, 'MIP', false, NULL, true, 'frasco de 20ml', 'frasco', 'Dipirona Sódica', 'Alívio de dores de cabeça, no corpo, febre e cólicas', '30 a 40 gotas a cada 6 horas (adultos)', 'Hipersensibilidade a pirazolonas ou asma induzida por analgésicos', 'EMS Genéricos', true),
('Novalgina 1g', ARRAY['novalgina', 'novalgina 1g', 'novalgina comprimido'], 18.90, 'MIP', false, NULL, true, 'caixa com 10 comprimidos', 'caixa', 'Dipirona Sódica', 'Dor intensa e febre alta resistente', '1 comprimido de 12 em 12 horas ou de 8 em 8 horas', 'Alergia a dipirona ou gravidez no último trimestre', 'Sanofi-Aventis', false),
('Paracetamol 500mg', ARRAY['paracetamol', 'paracetamol comprimido'], 7.90, 'MIP', false, NULL, true, 'caixa com 20 comprimidos', 'caixa', 'Paracetamol', 'Redução da febre e alívio temporário de dores leves', '1 a 2 comprimidos a cada 6 horas se necessário', 'Doença de fígado grave (insuficiência hepática grave)', 'Medley Genéricos', true),
('Tylenol 750mg', ARRAY['tylenol', 'tylenol 750mg'], 15.00, 'MIP', false, NULL, true, 'caixa com 20 comprimidos', 'caixa', 'Paracetamol', 'Alívio rápido de dores de dente, musculares, articulares e febre', '1 comprimido a cada 6 horas', 'Doença hepática activa ou alcoolismo crônico', 'Kenvue S.A.', false),
('Buscopan Composto', ARRAY['buscopan', 'buscopan composto', 'buscopan comprimido'], 18.50, 'MIP', false, NULL, true, 'caixa com 20 comprimidos', 'caixa', 'Butilbrometo de Escopolamina + Dipirona', 'Dores de cólica no estômago, intestino, rins e vias biliares', '1 a 2 comprimidos de 8 em 8 horas', 'Alergia a dipirona, glaucoma ou miastenia grave', 'Boehringer Ingelheim', false),
('Butilbrometo de Escopolamina', ARRAY['butilbrometo', 'escopolamina', 'buscopan generico'], 9.90, 'MIP', false, NULL, true, 'caixa com 20 comprimidos', 'caixa', 'Butilbrometo de Escopolamina', 'Tratamento de cólicas gastrointestinais e uterinas', '1 comprimido até 4 vezes ao dia', 'Glaucoma agudo ou aumento da próstata', 'Neo Química', true),
('Neosaldina', ARRAY['neosaldina', 'neosa', 'neosaldina comprimido'], 21.90, 'MIP', false, NULL, true, 'caixa com 20 comprimidos', 'caixa', 'Dipirona + Mucato de Isometepteno + Cafeína', 'Tratamento de dor de cabeça crônica e crises de enxaqueca', '1 a 2 comprimidos a cada 6 horas se houver sintomas', 'Hipertensão descontrolada ou alergia a dipirona', 'Takeda Pharma', false),
('Neosoro', ARRAY['neosoro', 'sorine', 'descongestionante', 'rinosoro'], 8.90, 'MIP', false, NULL, true, 'frasco de 30ml', 'frasco', 'Cloridrato de Naftazolina', 'Descongestionamento nasal rápido por gripes ou sinusites', '2 a 4 gotas em cada narina até 4 vezes ao dia', 'Glaucoma de ângulo estreito ou uso com antidepressivos IMAO', 'Neo Química', false),
('Dorflex', ARRAY['dorflex', 'dorflex comprimido'], 14.50, 'MIP', false, NULL, true, 'caixa com 36 comprimidos', 'caixa', 'Dipirona + Citrato de Orfenadrina + Cafeína Anidra', 'Alívio da dor muscular decorrente de contraturas dolorosas', '1 a 2 comprimidos até 4 vezes ao dia', 'Glaucoma, fraqueza muscular grave ou alergia a dipirona', 'Sanofi-Aventis', false),
('Advil 400mg', ARRAY['advil', 'ibuprofeno comprimido'], 18.90, 'MIP', false, NULL, true, 'caixa com 8 cápsulas gelatinosas', 'caixa', 'Ibuprofeno', 'Redução rápida de inflamações, dor de garganta, muscular e dente', '1 cápsula mole a cada 8 horas', 'Úlcera gástrica ativa ou asma desencadeada por anti-inflamatórios', 'Haleon Brasil', false),
('Ibuprofeno 600mg', ARRAY['ibuprofeno', 'ibuprofeno generico'], 10.90, 'MIP', false, NULL, true, 'caixa com 20 comprimidos', 'caixa', 'Ibuprofeno', 'Tratamento de processos inflamatórios e de dor intensa', '1 comprimido a cada 12 horas pós-refeição', 'Sangramento gastrointestinal ou insuficiência renal severa', 'Prati-Donaduzzi', true),
('Eno Efervescente', ARRAY['eno', 'sal de fruta eno', 'sal de fruta'], 6.90, 'MIP', false, NULL, true, 'envelope de 5g', 'envelope', 'Bicarbonato de Sódio + Carbonato de Sódio + Ácido Cítrico', 'Azia, queimação no estômago e má digestão em segundos', '1 envelope dissolvido em um copo d''água se necessário', 'Hipertensão severa ou dieta restritiva de sódio', 'Haleon Brasil', false),
('Sonrisal', ARRAY['sonrisal'], 5.50, 'MIP', false, NULL, true, 'caixa com 2 comprimidos efervescentes', 'caixa', 'Ácido Acetilsalicílico + Carbonato de Sódio', 'Indigestão ácida acompanhada de dor de cabeça', '1 a 2 comprimidos efervescentes dissolvidos em água', 'Alergia a AAS, asma ou histórico de sangramento gástrico', 'Haleon Brasil', false),
('Estomazil', ARRAY['estomazil'], 7.90, 'MIP', false, NULL, true, 'caixa com 6 envelopes', 'caixa', 'Bicarbonato de Sódio + Carbonato de Cálcio', 'Alívio rápido de queimação estomacal e refluxo ácido', '1 envelope dissolvido em meio copo de água', 'Insuficiência renal grave ou hipocalcemia', 'Hypera Pharma', false),
('Luftal Gotas', ARRAY['luftal', 'simeticona', 'luftal gotas'], 16.20, 'MIP', false, NULL, true, 'frasco de 15ml', 'frasco', 'Simeticona', 'Alívio de excesso de gases no estômago e intestino', '10 a 20 gotas até 3 vezes ao dia', 'Nenhuma contraindicação severa relatada', 'Reckitt Benckiser', false),
('Benegrip', ARRAY['benegrip', 'antigripal'], 14.90, 'MIP', false, NULL, true, 'caixa com 12 comprimidos', 'caixa', 'Dipirona + Maleato de Clorfeniramina + Cafeína', 'Alívio dos sintomas decorrentes de gripe e resfriados', '1 comprimido verde e 1 amarelo ao mesmo tempo até 4 vezes ao dia', 'Alergia a dipirona, glaucoma ou hipertensão grave', 'Hypera Pharma', false),
('Cimegripe', ARRAY['cimegripe'], 10.90, 'MIP', false, NULL, true, 'caixa com 20 cápsulas', 'caixa', 'Paracetamol + Maleato de Clorfeniramina + Fenilefrina', 'Febre, dores corporais, coriza e nariz entupido por resfriado', '1 cápsula a cada 4 horas', 'Problemas de tireoide ou doença cardíaca coronária grave', 'Cimed Indústria', false),
('Resfenol', ARRAY['resfenol'], 13.90, 'MIP', false, NULL, true, 'caixa com 20 cápsulas', 'caixa', 'Paracetamol + Clorfeniramina + Cloridrato de Fenilefrina', 'Alívio sintomático da gripe e congestão nasal', '1 cápsula de 4 em 4 horas', 'Doença hepática ativa ou hipertensão grave', 'Kley Hertz', false),
('Strepsils pastilha', ARRAY['strepsils', 'pastilha para garganta'], 18.90, 'MIP', false, NULL, true, 'caixa com 8 pastilhas', 'caixa', 'Flurbiprofeno', 'Alívio da dor e inflamação da garganta inflamada', 'Dissolver 1 pastilha na boca a cada 3 a 6 horas', 'Histórico de asma induzida por AINEs ou úlcera ativa', 'Reckitt Benckiser', false),
('Benalet pastilhas', ARRAY['benalet'], 14.50, 'MIP', false, NULL, true, 'caixa com 12 pastilhas', 'caixa', 'Cloridrato de Difenhidramina', 'Alívio sintomático da tosse irritativa e dor de garganta', 'Dissolver 1 pastilha lentamente a cada 2 ou 3 horas', 'Uso com sedativos, asma aguda ou menores de 12 anos', 'Kenvue S.A.', false),
('Flogoral Spray', ARRAY['flogoral'], 26.90, 'MIP', false, NULL, true, 'frasco spray de 30ml', 'frasco', 'Cloridrato de Benzidamina', 'Dor e inflamação na boca e garganta (aftas, amigdalite)', '2 a 6 nebulizações na garganta de 4 a 6 vezes ao dia', 'Hipersensibilidade à benzidamina', 'Aché Laboratórios', false),
('Cataflan Emulgel', ARRAY['cataflan', 'cataflan emulgel', 'pomada cataflan'], 29.90, 'MIP', false, NULL, true, 'bisnaga de 60g', 'bisnaga', 'Diclofenaco Dietilamônio', 'Alívio local de dor por contusões, torções e dores nas costas', 'Aplicar na região dolorida massageando levemente até 4 vezes ao dia', 'Terceiro trimestre de gravidez ou feridas na pele', 'Novartis Pharma', false),
('Lubrificante KY', ARRAY['ky', 'lubrificante ky', 'gel ky', 'lubrificante'], 24.90, 'MIP', false, NULL, true, 'bisnaga de 50g', 'bisnaga', 'Glicerol + Água (Gel à base de água)', 'Lubrificação íntima para alívio da secura vaginal', 'Aplicar quantidade desejada na região íntima', 'Hipersensibilidade aos componentes da fórmula', 'Kenvue S.A.', false),
('Preservativo Jontex', ARRAY['jontex', 'camisinha', 'preservativo'], 12.00, 'MIP', false, NULL, true, 'pacote com 3 unidades', 'pacote', 'Látex Natural', 'Planejamento familiar e prevenção de ISTs', 'Colocar antes de iniciar qualquer contato genital', 'Alergia conhecida ao látex de borracha natural', 'Reckitt Benckiser', false),
('Protetor Solar Sundown SPF 50', ARRAY['sundown', 'protetor solar'], 49.90, 'MIP', false, NULL, true, 'frasco de 120ml', 'frasco', 'Filtros químicos UVA/UVB', 'Prevenção de queimaduras solares e envelhecimento precoce', 'Aplicar abundantemente antes da exposição solar e reaplicar a cada 2 horas', 'Irritação de pele grave aos componentes', 'Kenvue S.A.', false),
('Xantinon', ARRAY['xantinon', 'xantinon comprimido', 'xanitinom'], 16.90, 'MIP', false, NULL, true, 'caixa com 20 comprimidos', 'caixa', 'Citrato de Colina + Metionina', 'Facilitação da digestão e eliminação de gorduras no fígado', '1 comprimido 3 vezes ao dia', 'Nenhuma contraindicação severa relatada', 'Mensa S.A.', false),
('Imosec 2mg', ARRAY['imosec', 'loperamida', 'imosec comprimido'], 18.90, 'MIP', false, NULL, true, 'caixa com 12 comprimidos', 'caixa', 'Cloridrato de Loperamida', 'Tratamento sintomático de diarreia aguda sem infecção bacteriana', '2 comprimidos iniciais, seguidos de 1 comprimido após evacuação líquida', 'Diarreia com febre alta ou fezes escuras e com sangue', 'Janssen-Cilag', false),
('Floratil 200mg', ARRAY['floratil', 'floratil capsula', 'floratil sachê'], 29.90, 'MIP', false, NULL, true, 'caixa com 6 cápsulas', 'caixa', 'Saccharomyces boulardii', 'Restauração da flora intestinal bacteriana benéfica', '1 cápsula duas vezes ao dia', 'Pacientes imunocomprometidos ou com cateter venoso central', 'Biocodex', false),
('Dramin B6', ARRAY['dramin', 'dramin b6', 'dramin comprimido'], 15.50, 'MIP', false, NULL, true, 'caixa com 20 comprimidos', 'caixa', 'Dimenidrinato + Piridoxina', 'Prevenção de náuseas, tonturas e vômitos por cinetose (viagens)', '1 comprimido de 4 em 4 horas se houver náusea', 'Porfiria aguda ou hipersensibilidade ao dimenidrinato', 'Takeda Pharma', false),
('Vonau Flash 4mg', ARRAY['vonau', 'vonau flash', 'ondansetrona'], 32.90, 'MIP', false, NULL, true, 'caixa com 10 comprimidos sublinguais', 'caixa', 'Cloridrato de Ondansetrona', 'Prevenção e tratamento rápido de enjoos e vômitos agudos', '1 comprimido sublingual dissolver na boca sob a língua', 'Uso concomitante com apomorfina', 'Biolab', false),
('Nebacetin', ARRAY['nebacetin', 'pomada nebacetin', 'neomicina'], 19.90, 'MIP', false, NULL, true, 'bisnaga de 15g', 'bisnaga', 'Sulfato de Neomicina + Bacitracina Zíncica', 'Tratamento de infecções de pele, cortes, ralados e pequenas queimaduras', 'Aplicar fina camada sobre a ferida 2 a 5 vezes ao dia', 'Feridas abertas extensas ou insuficiência renal grave', 'Takeda Pharma', false),
('Tandrilax', ARRAY['tandrilax', 'tandrilax comprimido', 'tandrilas'], 28.50, 'MIP', false, NULL, true, 'caixa com 30 comprimidos', 'caixa', 'Carisoprodol + Cafeína + Diclofenaco Sódico + Paracetamol', 'Espasmos musculares dolorosos, gota e reumatismo', '1 comprimido a cada 12 horas', 'Úlcera ativa, hipertensão grave ou doença cardíaca instável', 'Aché Laboratórios', false),
('Loratadina 10mg', ARRAY['loratadina', 'loratadina comprimido'], 14.20, 'MIP', false, NULL, true, 'caixa com 12 comprimidos', 'caixa', 'Loratadina', 'Rinite alérgica, espirros, coceira no nariz e olhos', '1 comprimido uma vez ao dia', 'Alergia a loratadina ou idade menor de 2 anos', 'Eurofarma Genéricos', true),
('Engov', ARRAY['engov', 'engov comprimido'], 9.90, 'MIP', false, NULL, true, 'caixa com 6 comprimidos', 'caixa', 'Maleato de Mepiramina + AAS + Hidróxido de Alumínio + Cafeína', 'Alívio sintomático da cefaleia decorrente de ressaca', '1 a 2 comprimidos antes ou após o consumo de álcool', 'Caso haja suspeita de dengue (contém AAS), hemofilia ou úlcera', 'Hypera Pharma', false),
('Epocler', ARRAY['epocler', 'flaconete epocler'], 3.50, 'MIP', false, NULL, true, 'flaconete de 10ml', 'flaconete', 'Citrato de Colina + Betaina + Metionina', 'Ação antitóxica no fígado após abusos alimentares ou de álcool', '1 flaconete até 3 vezes ao dia antes das principais refeições', 'Insuficiência renal grave', 'Hypera Pharma', false),
('Aspirina 500mg', ARRAY['aspirina', 'acido acetilsalicilico'], 11.50, 'MIP', false, NULL, true, 'caixa com 10 comprimidos', 'caixa', 'Ácido Acetilsalicílico', 'Dores de cabeça tensionais e febre moderada', '1 a 2 comprimidos a cada 4 ou 6 horas', 'Hemofilia, úlcera ou suspeita de dengue', 'Bayer S.A.', false),
('Bepantol Derma', ARRAY['bepantol', 'bepantol derma', 'pomada bepantol'], 34.90, 'MIP', false, NULL, true, 'bisnaga de 20g', 'bisnaga', 'Dexpantenol', 'Proteção e cicatrização acelerada de assaduras e pele ressecada', 'Aplicar fina camada sobre a pele limpa sempre que necessário', 'Hipersensibilidade aos componentes', 'Bayer S.A.', false),
('Hipoglós Amêndoas', ARRAY['hipoglos', 'pomada hipoglos'], 18.90, 'MIP', false, NULL, true, 'bisnaga de 40g', 'bisnaga', 'Óxido de Zinco + Vitaminas A e D + Óleo de Amêndoas', 'Prevenção e tratamento de assaduras em bebês e adultos', 'Aplicar a cada troca de fraldas ou conforme necessidade na pele seca', 'Lesões de pele abertas e infeccionadas', 'Johnson & Johnson', false),
('Losartana 50mg', ARRAY['losartana', 'losartana 50mg', 'losartana comprimido'], 14.90, 'Tarja Vermelha', true, 'simples', true, 'caixa com 30 comprimidos', 'caixa', 'Losartana Potássica', 'Hipertensão arterial crônica e insuficiência cardíaca crônica', '1 comprimido pela manhã', 'Uso de alisquireno em pacientes diabéticos', 'EMS Genéricos', true),
('Omeprazol 20mg', ARRAY['omeprazol', 'omeprazol 20mg'], 22.00, 'Tarja Vermelha', true, 'simples', true, 'caixa com 28 cápsulas', 'caixa', 'Omeprazol', 'Tratamento de gastrite aguda, refluxo esofágico e úlceras', '1 cápsula pela manhã em jejum de 30 minutos antes do café', 'Uso combinado com nelfinavir', 'EMS Genéricos', true),
('Pantoprazol 40mg', ARRAY['pantoprazol', 'pantoprazol 40mg'], 38.00, 'Tarja Vermelha', true, 'simples', true, 'caixa com 28 comprimidos', 'caixa', 'Pantoprazol', 'Doença de refluxo grave e esofagite erosiva moderada', '1 comprimido ao dia antes do café da manhã', 'Doença hepática moderada a grave', 'Eurofarma Genéricos', true),
('Allegra 120mg', ARRAY['allegra', 'allegra 120mg', 'desalex', 'antialergico', 'claritin'], 34.90, 'Tarja Vermelha', true, 'simples', true, 'caixa com 10 comprimidos', 'caixa', 'Cloridrato de Fexofenadina', 'Rinite alérgica crônica e urticária cutânea leve', '1 comprimido uma vez ao dia pela manhã', 'Menores de 12 anos ou gravidez sem orientação médica', 'Sanofi-Aventis', false),
('Nimesulida 100mg', ARRAY['nimesulida', 'nimesulida 100mg'], 12.50, 'Tarja Vermelha', true, 'simples', true, 'caixa com 12 comprimidos', 'caixa', 'Nimesulida', 'Dor aguda, processos inflamatórios de garganta, articulações e febre', '1 comprimido de 12 em 12 horas após as refeições', 'Insuficiência hepática, úlcera péptica ou asma por AAS', 'Medley Genéricos', true),
('Meloxicam 15mg', ARRAY['meloxicam', 'meloxicam 15mg'], 18.90, 'Tarja Vermelha', true, 'simples', true, 'caixa com 10 comprimidos', 'caixa', 'Meloxicam', 'Tratamento de artrite reumatoide crônica e osteoartrite dolorosa', '1 comprimido de 15mg uma vez ao dia', 'Insuficiência renal grave ou sangramento gástrico ativo', 'Eurofarma Genéricos', true),
('Sinvastatina 20mg', ARRAY['sinvastatina', 'remedio de colesterol'], 16.00, 'Tarja Vermelha', true, 'simples', true, 'caixa com 30 comprimidos', 'caixa', 'Sinvastatina', 'Redução dos níveis elevados de colesterol total, LDL e triglicerídeos', '1 comprimido à noite antes de dormir', 'Doença hepática activa ou gravidez confirmada', 'Medley Genéricos', true),
('Puran T4 50mcg', ARRAY['puran', 'puran t4', 'levotiroxina', 'remedio de tireoide'], 19.50, 'Tarja Vermelha', true, 'simples', true, 'caixa com 30 comprimidos', 'caixa', 'Levotiroxina Sódica', 'Terapia de reposição de hormônio da tireoide no hipotireoidismo', '1 comprimido ao dia em jejum total de pelo menos 30 a 60 minutos', 'Insuficiência adrenal não tratada ou infarto agudo recente', 'Sanofi-Aventis', false),
('Sertralina 50mg', ARRAY['sertralina', 'sertralina 50mg'], 35.00, 'Tarja Vermelha', true, 'simples', true, 'caixa com 30 comprimidos', 'caixa', 'Cloridrato de Sertralina', 'Tratamento de depressão crônica, ansiedade social, TOC e pânico', '1 comprimido pela manhã ou à noite', 'Uso combinado com inibidores da MAO ou pimozida', 'Teuto Genéricos', true),
('Fluoxetina 20mg', ARRAY['fluoxetina', 'fluoxetina 20mg'], 28.00, 'Tarja Vermelha', true, 'simples', true, 'caixa com 30 comprimidos', 'caixa', 'Cloridrato de Fluoxetina', 'Tratamento da depressão, transtorno disfórico pré-menstrual e bulimia', '1 cápsula pela manhã', 'Uso combinado de IMAOs ou tioridazina', 'Neo Química Genéricos', true),
('Escitalopram 10mg', ARRAY['escitalopram', 'escitalopram 10mg'], 48.00, 'Tarja Vermelha', true, 'simples', true, 'caixa com 30 comprimidos', 'caixa', 'Oxalato de Escitalopram', 'Ansiedade generalizada, depressão unipolar e agorafobia', '1 comprimido de 10mg ao dia', 'Prolongamento do intervalo QT no eletrocardiograma', 'Eurofarma Genéricos', true),
('Metformina 850mg', ARRAY['metformina', 'glifage', 'glifage xr', 'metformina 850mg'], 15.00, 'Tarja Vermelha', true, 'simples', true, 'caixa com 30 comprimidos', 'caixa', 'Cloridrato de Metformina', 'Controle de glicemia em diabetes mellitus tipo 2', '1 comprimido duas vezes ao dia durante refeições', 'Insuficiência renal grave (gfr inferior a 30ml/min)', 'EMS Genéricos', true),
('Aerolin Spray', ARRAY['aerolin', 'aerolin spray', 'bombinha aerolin', 'salbutamol'], 26.50, 'Tarja Vermelha', true, 'simples', true, 'frasco spray de 200 doses', 'frasco', 'Sulfato de Salbutamol', 'Alívio rápido de falta de ar crônica por asma ou bronquite', '1 a 2 inalações jateadas em crises de espasmo brônquico', 'Alergia ao salbutamol ou arritmia cardíaca acelerada grave', 'GlaxoSmithKline (GSK)', false),
('Tadalafila 5mg', ARRAY['tadalafila', 'tadalafina', 'tadalafila 5mg'], 29.90, 'Tarja Vermelha', true, 'simples', true, 'caixa com 30 comprimidos', 'caixa', 'Tadalafila', 'Disfunção erétil e tratamento de hiperplasia prostática benigna', '1 comprimido uma vez ao dia no mesmo horário', 'Uso de medicamentos doadores de óxido nítrico ou nitratos', 'Eurofarma Genéricos', true),
('Amoxicilina 500mg', ARRAY['amoxicilina', 'amoxicilina 500mg', 'amoxilina'], 28.00, 'Antibiótico', true, 'retida', true, 'caixa com 21 cápsulas', 'caixa', 'Amoxicilina tri-hidratada', 'Infecções respiratórias superiores, amigdalite e pneumonia bacteriana', '1 cápsula de 8 em 8 horas por 7 a 10 dias', 'Alergia a penicilinas e derivados beta-lactâmicos', 'Eurofarma Genéricos', true),
('Azitromicina 500mg', ARRAY['azitromicina', 'azitromicina 500mg', 'zitromax'], 24.50, 'Antibiótico', true, 'retida', true, 'caixa com 5 comprimidos', 'caixa', 'Azitromicina di-hidratada', 'Infecções bacterianas das vias aéreas e infecções de pele leves', '1 comprimido de 500mg ao dia por 3 a 5 dias', 'Histórico de icterícia associada ao uso deste antibiótico', 'EMS Genéricos', true),
('Cefalexina 500mg', ARRAY['cefalexina', 'cefalexina 500mg'], 39.90, 'Antibiótico', true, 'retida', true, 'caixa com 40 comprimidos', 'caixa', 'Cefalexina monoidratada', 'Infecções bacterianas de tecidos moles, urinárias e ósseas', '1 comprimido a cada 6 horas por 7 a 14 dias', 'Alergia grave a cefalosporinas ou penicilina', 'Medley Genéricos', true),
('Ciprofloxacino 500mg', ARRAY['ciprofloxacino', 'cipro'], 32.00, 'Antibiótico', true, 'retida', true, 'caixa com 14 comprimidos', 'caixa', 'Cloridrato de Ciprofloxacino', 'Infecções urinárias graves, diarreia bacteriana e otite média', '1 comprimido a cada 12 horas por 3 a 7 dias', 'Uso concomitante com tizanidina ou gravidez', 'Eurofarma Genéricos', true),
('Bactrim', ARRAY['bactrim', 'bactrim comprimido'], 21.00, 'Antibiótico', true, 'retida', true, 'caixa com 20 comprimidos', 'caixa', 'Sulfametoxazol + Trimetoprima', 'Infecções bacterianas respiratórias, urinárias e renais', '1 comprimido a cada 12 horas por 10 dias', 'Disfunção hepática crônica grave ou anemia megaloblástica', 'Roche S.A.', false),
('Rivotril 2mg', ARRAY['rivotril', 'clonazepam', 'rivotril 2mg'], 19.90, 'Tarja Preta', true, 'azul', false, 'caixa com 30 comprimidos', 'caixa', 'Clonazepam', 'Espasmos musculares, ansiedade patológica crônica, crises focais e fobia social', '0.5mg a 2mg ao deitar ou conforme receita controlada', 'Glaucoma agudo ou insuficiência respiratória grave', 'Roche S.A.', false),
('Ritalina 10mg', ARRAY['ritalina', 'ritalina 10mg', 'metilfenidato'], 45.00, 'Tarja Preta', true, 'azul', false, 'caixa com 60 comprimidos', 'caixa', 'Cloridrato de Metilfenidato', 'Transtorno de Déficit de Atenção e Hiperatividade (TDAH) e narcolepsia', '1 comprimido pela manhã e 1 após almoço', 'Psicose ativa, tiques motores severos ou glaucoma de ângulo fechado', 'Novartis Pharma', false),
('Lexotan 3mg', ARRAY['lexotan', 'bromazepam', 'lexotan 3mg'], 26.90, 'Tarja Preta', true, 'azul', false, 'caixa com 30 comprimidos', 'caixa', 'Bromazepam', 'Ansiedade acentuada, tension, depressão ansiosa crônica e insônia', '1.5mg a 3mg até 3 vezes ao dia conforme prescrição', 'Miastenia grave ou insuficiência pulmonar crônica grave', 'Roche S.A.', false),
('Frontal 0.5mg', ARRAY['frontal', 'alprazolam', 'frontal 0.5mg'], 38.50, 'Tarja Preta', true, 'azul', false, 'caixa com 30 comprimidos', 'caixa', 'Alprazolam', 'Ansiedade reativa, pânico, fobia social e insônia tensional', '1 comprimido ao deitar ou de 12 em 12 horas', 'Glaucoma agudo de ângulo fechado', 'Pfizer Brasil', false),
('Diazepam 10mg', ARRAY['diazepam', 'diazepam 10mg'], 15.00, 'Tarja Preta', true, 'azul', false, 'caixa com 30 comprimidos', 'caixa', 'Diazepam', 'Tensão ansiosa crônica, abstinência alcoólica ou espasmos musculares', '5mg a 10mg ao deitar ou conforme orientação', 'Alergia a benzodiazepínicos, dependência de drogas', 'Eurofarma Genéricos', true),
('Stilnox 10mg', ARRAY['stilnox', 'zolpidem', 'stilnox 10mg'], 62.00, 'Tarja Preta', true, 'azul', false, 'caixa com 20 comprimidos', 'caixa', 'Hemitartarato de Zolpidem', 'Tratamento de curto prazo da insônia grave ou incapacitante', '1 comprimido sublingual ou oral ao deitar imediatamente', 'Insuficiência respiratória severa ou apneia do sono', 'Sanofi-Aventis', false),
('Venvanse 30mg', ARRAY['venvanse', 'lisdexanfetamina', 'venvanse 30mg'], 390.00, 'Tarja Preta', true, 'azul', false, 'caixa com 28 cápsulas', 'caixa', 'Dimesilato de Lisdexanfetamina', 'Tratamento de TDAH em crianças e adultos e transtorno de compulsão alimentar', '1 cápsula ao dia pela manhã', 'Cardiopatia grave, arteriosclerose avançada ou hipertensão grave', 'Takeda Pharma', false),
('Sibutramina 15mg', ARRAY['sibutramina', 'sibutramina 15mg'], 54.00, 'Tarja Preta', true, 'azul', false, 'caixa com 30 cápsulas', 'caixa', 'Cloridrato de Sibutramina', 'Tratamento auxiliar de perda de peso em obesidade com IMC > 30', '1 cápsula ao dia em jejum pela manhã', 'Histórico de doença arterial coronariana, derrame (AVC) ou arritmia', 'Eurofarma Genéricos', true),
('Gardenal 100mg', ARRAY['gardenal', 'fenobarbital', 'gardenal 100mg'], 14.20, 'Tarja Preta', true, 'azul', false, 'caixa com 20 comprimidos', 'caixa', 'Fenobarbital', 'Prevenção e controle de crises convulsivas de epilepsia e convulsões tônico-clônicas', '1 comprimido à noite antes de deitar', 'Porfiria intermitente aguda ou insuficiência hepática severa', 'Sanofi-Aventis', false),
('Roacutan 20mg', ARRAY['roacutan', 'isotretinoina', 'roacutan 20mg'], 150.00, 'Especial', true, 'especial', false, 'caixa com 30 cápsulas', 'caixa', 'Isotretinoína', 'Tratamento de formas graves de acne vulgar (nódulo-cística e conglobata) resistentes', '0.5 a 1.0 mg/kg ao dia conforme receita especial e peso', 'Mulheres em idade fértil sem contracepção ativa (risco extremo de malformação fetal)', 'Roche S.A.', false);
